server: 
  error:
    include-message: always
    include-binding-errors: always
spring: 
  application:
    name: api
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
imagekit:
  private-key: ${IMAGEKIT_PRIVATE_KEY}
  public-key: ${IMAGEKIT_PUBLIC_KEY}